puts "🌱 Seeding FF..."

Cart.destroy_all
CartItem.destroy_all
Item.destroy_all
User.destroy_all



#USER
user1 = User.create(first_name: "Zack", last_name: "Hall", email: "zackh@gmail.com", billing_address: "123 Navy Lane,Oak Harbor,WA,98277", shipping_address: "456 Squirel Ave,Oak Harbor,WA,98277", phone_number: "123-456-7890", password: "Zack123", username: "Zack123")
user2 = User.create(first_name: "Kayle", last_name: "Davis", email: "kayled@gmail.com", billing_address: "123 Navy Lane,Oak Harbor,WA,98277", shipping_address: "456 Squirel Ave,Oak Harbor,WA,98277", phone_number: "123-456-7890", password: "Kayle123", username: "Kayle123")

#---------------------------------ITEMS-------------------------------------------------------- 
#Final Fantasy 7 ----------------
#Bedding
finalfantasyseven1 = Item.create(name: "Medley Throw Blanket", image: "https://ctl.s6img.com/society6/img/oifrrLRyOiC07f_L97bxozfq1RE/h_264,w_264/throw-blankets/small/full/~artwork,fw_5525,fh_6500,fx_-488,iw_6500,ih_6500/s6-original-art-uploads/society6/uploads/misc/356d93b96ba7420f88b6fb1d2130b58d/~~/final-fantasy-medley-throw-blankets.jpg?wait=0&attempt=0", category: "Bedding", description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.", game: "Final Fantasy 7", price: "59.99", quantity: 10)
finalfantasyseven2 = Item.create(name: "Embrace Throw Blanket", image: "https://ctl.s6img.com/society6/img/uWBwsMEzDyUMM42F4M1X9S2wNL0/h_264,w_264/throw-blankets/small/full/~artwork,fw_5525,fh_6500,fy_-894,iw_5525,ih_8287/s6-original-art-uploads/society6/uploads/misc/b23d0b7959e84b1ca70e9504d1c87058/~~/final-fantasy-vii5834436-throw-blankets.jpg?wait=0&attempt=0", category: "Bedding", description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.", game: "Final Fantasy 7", price: "59.99", quantity: 10)
finalfantasyseven3 = Item.create(name: "More Weight Throw Blanket", image: "https://ctl.s6img.com/society6/img/Gl2OrIt4xh5AMilBHr4BCIAplUw/h_264,w_264/throw-blankets/small/full/~artwork,fw_5525,fh_6500,fy_-894,iw_5525,ih_8287/s6-original-art-uploads/society6/uploads/misc/2fcdc6170fbd488bad593fcb1fce37bd/~~/final-fantasy-vii5834896-throw-blankets.jpg?wait=0&attempt=0", category: "Bedding", description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.", game: "Final Fantasy 7", price: "59.99", quantity: 10)
finalfantasyseven4 = Item.create(name: "Cloud Strife Throw Blanket", image: "https://ctl.s6img.com/society6/img/Dhdr8UdGMtd4UFJXkRU3jptSgQ4/h_264,w_264/throw-blankets/small/full/~artwork,fw_6500,fh_5525,fx_-664,iw_7827,ih_5525/s6-original-art-uploads/society6/uploads/misc/fe3039322ac44268b3c4658602996218/~~/cloud-strife-ffvii-remake-throw-blankets.jpg?wait=0&attempt=0", category: "Bedding", description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.", game: "Final Fantasy 7", price: "59.99", quantity: 10)
#Mug
finalfantasyseven3 = Item.create(name: "Final fantasy 7, cloud strife, japanese ink splatter, coffee mug, anime mug, sephiroth, ff7", image: "https://i.etsystatic.com/29560732/r/il/3045c0/3126854068/il_794xN.3126854068_eru3.jpg", category: "Mug" , description: "High quality mug makes the perfect gift for everyone.Printed on only the highest quality mugs. The print will never fade no matter how many times it is washed." ,game: "Final Fantasy 7", price: "18.95", quantity: 20)
finalfantasyseven4 = Item.create(name: "Tifa's 7th Heaven - Final Fantasy Mug", image: "https://i.etsystatic.com/31399270/c/1919/1526/0/188/il/0fc595/3522822708/il_340x270.3522822708_4lh3.jpg", category: "Mug" , description: "Whenever you're planning the destruction of your local reactor or simply enjoying a nice breakfast, be sure to always drink your coffee in this mug! I'm sure the local cute bar's owner will thank you!" ,game: "Final Fantasy 7", price: "15.00", quantity: 20)
#Bag
finalfantasyseven8 = Item.create(name: "Messenger Bag: Shinra Company / Final Fantasy VII / Cloud", image: "https://i.etsystatic.com/7282319/r/il/cff21d/1750827269/il_794xN.1750827269_9s3z.jpg" , category: "Bag" , description: "Sport this cool bag to fight your way through to become a First Class Soldier like Sephiroth had, and Cloud well, pretended to" ,game: "Final Fantasy 7" , price: "72.00", quantity: 50)
finalfantasyseven9 = Item.create(name: "Wiz Chocobo Post Canvas Messenger Bag - Cotton Canvas Bag", image: "https://i.etsystatic.com/32767512/r/il/43f6f9/3540353114/il_794xN.3540353114_p7s8.jpg" , category: "Bag" , description: "Wiz Chocobo Post Canvas Messenger Bag" ,game: "Final Fantasy 7" , price: "45.00", quantity: 50)
finalfantasyseven10 = Item.create(name: "Final Fantasy 7 Memories FF7 Backpack Bag", image: "https://i.etsystatic.com/26081505/r/il/eef8c3/3169648134/il_794xN.3169648134_dngg.jpg" , category: "Bag" , description: "Final Fantasy 7 Memories FF7 Backpack Bag Gaming Gamer Cool Cute Gift Gifts" ,game: "Final Fantasy 7" , price: "66.81", quantity: 50)
finalfantasyseven11 = Item.create(name: "Moogle Final Fantasy Messenger Bag or Pillow", image: "https://i.etsystatic.com/6647590/r/il/e0c9b2/3182822107/il_794xN.3182822107_qbxb.jpg" , category: "Bag" , description: "Cute Moogle is appliqued with interesting fabrics to create a unique look, on a cotton messenger bag. The bag is lined with coordinating fabric and has a pocket across the back divided into two sections, one 4inch wide for your cell phone." ,game: "Final Fantasy 7" , price: "54.95", quantity: 50)
#Keychain
finalfantasyseven15 = Item.create(name: "Final Fantasy 7 Cloud Strife acrylic keychain", image: "https://i.etsystatic.com/24889907/r/il/d0794b/3564854404/il_794xN.3564854404_fflu.jpg", category: "KeyChain", description: "Cute acrylic holographic shard charm of Cloud Strife folding a mini Sephiroth", game: "Final Fantasy 7" , price: "11.99" , quantity: 80 )
finalfantasyseven15 = Item.create(name: "Moogle Final Fantasy X Yin & Yang Keychain/Necklace", image: "https://i.etsystatic.com/14466015/r/il/7ebf11/1519568909/il_794xN.1519568909_azzj.jpg", category: "KeyChain", description: "This adorable medallion was made with all final fantasy lovers in mind. The Moogle is perhaps the cutest little creature in all of Eorzea and is perfectly displayed in this piece as yin & yang. We knew we just had to add some Moogle's to the shop!", game: "Final Fantasy 7" , price: "10.95" , quantity: 80 )
#Apparel
finalfantasyseven21 = Item.create(name: "Final Fantasy VII Premium T-Shirt" , image: "https://i.etsystatic.com/9353904/c/1613/1282/151/68/il/3830fc/3028583680/il_340x270.3028583680_orut.jpg", category: "Apparel", description: "This is a Premium Cotton Screen Printed T-Shirt. All of our products are ultra soft, lightweight, premium made, and of the highest quality.",game: "Final Fantasy 7", price:"20.00", quantity: 20 )
finalfantasyseven23 = Item.create(name: "Knives Don’t Kill People Tonberry Does Shirt" , image: "https://i.etsystatic.com/23778451/r/il/78561c/3266790501/il_794xN.3266790501_qhoy.jpg", category: "Apparel", description: "SOLID COLORS: 100% ringspun cotton. Pre-shrunk. Shoulder-to-shoulder taping. Quarter-turned to avoid crease down the center. Machine wash cold with like colors, dry low heat. Great for Daily and Casual Wear, High Softness & Wearability.",game: "Final Fantasy 7", price:"18.12", quantity: 20 )
finalfantasyseven24 = Item.create(name: "Chocobo Racing Tee - Final Fantasy 7 - 100% Cotton Gildan 64000 Unisex Softstyle" , image: "https://i.etsystatic.com/23232417/r/il/123c79/3037200244/il_794xN.3037200244_qxsv.jpg", category: "Apparel", description: "Chocobo Racing Square from The Gold Saucer in FFVII",game: "Final Fantasy 7", price:"22.70", quantity: 20 )
finalfantasyseven25 = Item.create(name: "CHOCOBO RIDERS" , image: "https://i.etsystatic.com/12943982/r/il/49d751/1843839252/il_794xN.1843839252_mmwi.jpg", category: "Apparel", description: "All the ShitCake Clothing's T-Shirts are handprinted by direct digital printing or by serigraphy, all our high quality t-shirts are 100% cotton and machine washable. We use only super high quality water ink, so non-toxic, that make our shirts light and long lasting.",game: "Final Fantasy 7", price:"41.39", quantity: 20 )
#Clock
finalfantasyseven15 = Item.create(name: "Game in the series Record Wall Clock", image: "https://i.etsystatic.com/20544792/r/il/a321b0/2703608448/il_794xN.2703608448_fye9.jpg", category: "Clock", description: "Vinyl record 12 inch wall clock", game: "Final Fantasy 7" , price: "178.00", quantity: 80 )
#Toy
finalfantasyseven39 = Item.create(name: "Final Fantasy VII Tifa and Cloud Cubic Diorama" , image: "https://i.etsystatic.com/19505621/r/il/f75e86/3066235972/il_794xN.3066235972_23e1.jpg", category: "Toy", description: "Cubic Diorama inspired by Final Fantasy VII video game. Handmade with hard cardboard, with high quality digital printing and hand cut photographic prints. All mounted on a hand-mounted transparent methacrylate cube.",game: "Final Fantasy 7", price:"92.49", quantity: 20)
finalfantasyseven40 = Item.create(name: "Final Fantasy 7 Sprites" , image: "https://i.etsystatic.com/10527355/r/il/fa7b3b/2399886749/il_794xN.2399886749_tbc9.jpg", category: "Toy", description: "These sprites are inspired by one of the greatest rpg's ever made - Final Fantasy 7.",game: "Final Fantasy 7", price:"30.00", quantity: 20)
finalfantasyseven41 = Item.create(name: "Final Fantasy 7 Remastered Buster Sword bookmark, 3d printed" , image: "https://i.etsystatic.com/22165323/r/il/009fb7/3411012517/il_794xN.3411012517_i55e.jpg", category: "Toy", description: " This is the more detailed remastered version of the Buster Sword, with a 2-tone blade and a must-have item to function as a conversation starting bookmark or an awesome display piece. However you use it, you won't be disappointed with its technological look and good busting design! The only thing it's missing is Materia!",game: "Final Fantasy 7", price:"12.49", quantity: 20)
finalfantasyseven45 = Item.create(name: "Mini Shadowbox Frame - Final Fantasy VII" , image: "https://i.etsystatic.com/31077158/r/il/c70d26/3549794673/il_794xN.3549794673_1bai.jpg", category: "Toy", description: "5x7x1/2 frame. Using four panes of glass, 2-4 layers of hand-cut photopaper are tiered to create a groovy 3-D visual of ideal interest. Perfect for walls, bookshelves, or desks; amongst other nerdy nostalgia.",game: "Final Fantasy 7", price:"30.00", quantity: 20)

#Final Fantasy 10 -------------
#Bedding
finalfantasyten1 = Item.create(name: "Final Fantasy Quilt Blanket", image: "https://img.btdmp.com/10118/10118461/products/0x540@16181970909e4b322897.jpeg", category: "Bedding", description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.",game: "Final Fantasy 10", price: "49.99", quantity: 10)
finalfantasyten2 = Item.create(name: "Final Fantasy X Fleece Blanket", image: "https://render.fineartamerica.com/images/rendered/default/flat/blanket/images/artworkimages/medium/1/final-fantasy-x-eloisa-mannion.jpg?&targetx=-235&targety=0&imagewidth=1422&imageheight=800&modelwidth=952&modelheight=800&backgroundcolor=E8EFF2&orientation=1&producttype=blanket-coral-50-60", category: "Bedding",  description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.",game: "Final Fantasy 10", price: "36.99", quantity: 10)
finalfantasyten3 = Item.create(name: "Final Fantasy X Throw Blanket", image: "https://ctl.s6img.com/society6/img/qeDynHg9czkmfYI1aIl6PFYu4Gg/w_700/throw-blankets/small/full/~artwork,fw_6500,fh_5525,iw_6500,ih_5525/s6-0047/a/20796758_9092150/~~/final-fantasy-x-d9x-throw-blankets.jpg?wait=0&attempt=0", category: "Bedding",description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.",  game: "Final Fantasy 10", price: "41.99", quantity: 10)
finalfantasyten4 = Item.create(name: "Wakka Portrait", image: "https://ih1.redbubble.net/image.1745921972.2331/ur,blanket_large_bed,square,x600.1.jpg", category: "Bedding",description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy.", game: "Final Fantasy 10", price: "68.18", quantity: 10)
#Mug
finalfantasyten3 = Item.create(name: "FFX Final Fantasy X Mug | Yuna Tidus Lulu Rikku Wakka Aaron", image: "https://i.etsystatic.com/19222097/r/il/ab5918/3419543134/il_794xN.3419543134_nch2.jpg", category: "Mug" , description: "FFX Mug,Handmade,Capacity: 15 fluid ounces" ,game: "Final Fantasy 10", price: "18.00", quantity: 20)
finalfantasyten4 = Item.create(name: "Final Fantasy Chocobo Mug Beer Stein Wooden Tankard Geek Gift for Gamer Wooden Beer Mug", image: "https://i.etsystatic.com/28458298/r/il/9cc71b/3432060131/il_794xN.3432060131_qdz8.jpg", category: "Mug" , description: "If you want to surprise or please somebody with a unique gift, our wooden beer mug is a great choice for this purpose!" ,game: "Final Fantasy 10", price: "29.99", quantity: 20)
#Bag
finalfantasyten8 = Item.create(name: "Summoner Yuna Weekender Bag", image: "https://i.etsystatic.com/21644039/r/il/13be09/2463987136/il_794xN.2463987136_qqau.jpg" , category: "Bag" , description: "Whether your weekend getaway is Besaid or the Jersey Shore, this Yuna-inspired bag has you covered! With a sturdy canvas outer and cream cotton liner, this roomy and durable tote is the perfect summer trip bag." ,game: "Final Fantasy 10" , price: "35.00", quantity: 50)
finalfantasyten9 = Item.create(name: "Wiz Chocobo Post Canvas Field Bag, Messenger Bag", image: "https://i.etsystatic.com/32767512/r/il/33d32f/3540365200/il_794xN.3540365200_q2wt.jpg" , category: "Bag" , description: "100% cotton canvas,Heavy enzyme-washed,Front flap with antique brass turn-buckles,Inside hanging zippered pocket" ,game: "Final Fantasy 10" , price: "25.00", quantity: 50)
finalfantasyten10 = Item.create(name: "Auron Portrait - Final Fantasy X Drawstring Bag", image: "https://ih1.redbubble.net/image.1745956553.3280/tb,840x840,medium-c,1,198,600,600-bg,f8f8f8.jpg" , category: "Bag" , description: "Spacious, sturdy, and sweet alternative to the traditional backpack" ,game: "Final Fantasy 10" , price: "38.45", quantity: 50)
finalfantasyten11 = Item.create(name: "Final Fantasy X Tote Bag", image: "https://ctl.s6img.com/society6/img/HFaDzE-1m6fLL4iqeD5D4gac2nA/w_700/bags/small/full/~artwork,fw_3500,fh_3500,iw_3500,ih_3500/s6-0047/a/20796808_13819600/~~/final-fantasy-x-d9x-bags.jpg" , category: "Bag" , description: "Our tote bags are constructed with a premium, canvas-like material and double-stitched for quality. They're available in three sizes, making them great reusable grocery bags or to bring to the beach." ,game: "Final Fantasy 10" , price: "24.99", quantity: 50)
#Keychain
finalfantasyten15 = Item.create(name: "Large Sterling Silver Tidus Necklace", image: "https://i.etsystatic.com/10114327/r/il/5fcfff/1102748291/il_794xN.1102748291_ep91.jpg", category: "KeyChain", description: "This is 925 Sterling Silver Tidus Necklace from Final Fantasy X. Pendant is made from 925 Sterling Silver. It comes with a stainless steel chain.", game: "Final Fantasy 10" , price: "65.00" , quantity: 80 )
finalfantasyten15 = Item.create(name: "RPG Battle Menu Keychain", image: "https://i.etsystatic.com/10467933/r/il/d211b3/2685842309/il_794xN.2685842309_qjrh.jpg", category: "KeyChain", description: "Where are my fantasy JRPG fans at? Check out this interpretation of a battle menu from one of the most iconic video games of the 90's. Show everyone how much you love this classic with this keychain.", game: "Final Fantasy 10" , price: "14.99" , quantity: 80 )
#Apparel
finalfantasyten21 = Item.create(name: "Yuna x Tidus - final fantasy X Tshirt" , image: "https://i.etsystatic.com/18088021/r/il/c00d42/3221842473/il_794xN.3221842473_boj5.jpg", category: "Apparel", description: "From the the final fantasy X art collections book Tidus and Yuna embraced in Macalania Woods All style 100% cotton",game: "Final Fantasy 10", price:"15.00", quantity: 20 )
finalfantasyten23 = Item.create(name: "Final Fantasy X Premium Hoodie - Screen Printed" , image: "https://i.etsystatic.com/9353904/r/il/800db5/3502952153/il_794xN.3502952153_t6dc.jpg", category: "Apparel", description: "All of our products are ultra soft, mediumweight, premium made, and of the highest quality.",game: "Final Fantasy 10", price:"40.00", quantity: 20 )
finalfantasyten24 = Item.create(name: "Unisex/Mens: Yevon Cup / Final Fantasy X / Blitzball t-shirt" , image: "https://i.etsystatic.com/7282319/r/il/a01ec8/1656704650/il_794xN.1656704650_2ph6.jpg", category: "Apparel", description: "Ladies and Gentlemen, come and see the Ace of the Zanarkand Abes! Sport this fresh t-shirt and let people know you're a true Final Fantasy and Blitzball Fan!",game: "Final Fantasy 10", price:"26.00", quantity: 20 )
finalfantasyten25 = Item.create(name: "Final Fantasy X FFX Yuna Casual Cosplay Gamer Gaming Thigh High Socks Accessory" , image: "https://i.etsystatic.com/7226913/r/il/b3ca83/1901604245/il_794xN.1901604245_hm15.jpg", category: "Apparel", description: "These cosplay accessory socks were inspired by Yuna of FFX (Final Fantasy X) from her summoner skirt outfit. Put on these fashionable socks as you embark on a pilgrimage as a summoner.",game: "Final Fantasy 10", price:"15.00", quantity: 20 )
#Clock
finalfantasyten15 = Item.create(name: "Final Fantasy 10 Vinyl Record Wall Clock, Auron", image: "https://barcodeindex.s3.amazonaws.com/images/798911985331.jpg", category: "Clock", description: "FANTASTIC GIFT for a happy Final Fantasy X lover will be proudly hanging on the wall creating an amazing look of a unique functional decor", game: "Final Fantasy 10" , price: "55.00", quantity: 80 )
#Toy
finalfantasyten39 = Item.create(name: "Final Fantasy X Chocobo Keychain - Chocobo Feather" , image: "https://i.etsystatic.com/14466015/r/il/1ae0e2/1422205789/il_794xN.1422205789_2w5x.jpg", category: "Toy", description: "The humble Chocobo, a mainstay since the old days of Final Fantasy! Their adorable beaked faces always offering a faster way to navigate the treacherous monster filled world. To this day Chocobos remain all important, showing up on the Gil currency and serving as a symbol of Final Fantasy history. Now you two can have your own lucky Chocobo to keep with you always!",game: "Final Fantasy 10", price:"10.95", quantity: 20)
finalfantasyten40 = Item.create(name: "FF10 Tidus Brotherhood Wall Art, Engraved Wood, Handmade" , image: "https://i.etsystatic.com/20634608/r/il/74d191/3478395726/il_794xN.3478395726_awfe.jpg", category: "Toy", description: "Show off your love for Final Fantasy X with handmade, engraved-wood wall art featuring Tidus with his signature sword, Brotherhood. Perfect for your own collection or as a gift for a FFX / FF10 fan!",game: "Final Fantasy 10", price:"45.00", quantity: 20)
finalfantasyten41 = Item.create(name: "Final Fantasy Bookmark Would You Like To Save Your Progress? - High Quality Bookmark" , image: "", category: "Toy", description: "This is a high quality bookmark, printed on 100 lb / 16 pt material.",game: "Final Fantasy 10", price:"3.99", quantity: 20)
finalfantasyten45 = Item.create(name: "Final Fantasy X Yuna & Her Guardians FFX Open Edition Art Print 11x17 inch" , image: "https://i.etsystatic.com/13594991/r/il/f4e7e8/2735195075/il_794xN.2735195075_4fm2.jpg", category: "Toy", description: "A wall art poster of Final Fantasy X with Tidus and Yuna and the rest of the crew. Perfect gift for gamers!
An open edition 11x17 print.",game: "Final Fantasy 10", price:"24.99", quantity: 20)


#Final Fantasy 15  ---------------------
#Bedding
finalfantasyfifteen1 = Item.create(name: "Chocobros (FFXV) Throw Blanket", image: "https://ih1.redbubble.net/image.1672171300.4247/ur,blanket_large_bed,square,x600.1.jpg", category: "Bedding", description: "Drape your bed, your couch, or yourself in soft, fluffy art", game: "Final Fantasy 15", price: "54.54", quantity: 10)
finalfantasyfifteen2 = Item.create(name: "Noctis Prompto Ignis Gladiolus Cosplay Small Blanket", image: "https://ae01.alicdn.com/kf/HTB1buRzaynrK1RjSsziq6xptpXaF/New-Anime-FF15-Final-Fantasy-XV-FFXV-Noctis-Prompto-Ignis-Gladiolus-Cosplay-Small-Blanket-Gifts.jpg_640x640.jpg_.webp", category: "Bedding", description: "Cozy up with our unbelievably soft throw blankets. Crafted with sherpa fleece, these blankets actually get softer the more times you wash them. Coordinate with throw pillows and rectangular pillows for whatever nook needs a little extra dose of comfy", game: "Final Fantasy 15", price: "40.99", quantity: 10)
finalfantasyfifteen3 = Item.create(name: "Galaxy FF15 white Throw Blanket", image: "https://ih1.redbubble.net/image.2932915218.4266/ur,blanket_large_bed,square,x600.1.jpg", category: "Bedding", description: "Drape your bed, your couch, or yourself in soft, fluffy art,100% polyester fleece", game: "Final Fantasy 15", price: "54.54", quantity: 10)
finalfantasyfifteen4 = Item.create(name: "Bedding Set Duvet Cover Set Bedroom Set Bedlinen", image: "https://cdn11.bigcommerce.com/s-vttfwx13mg/images/stencil/1280x1280/products/172866/1277138/TL11041705__77021__29857__02025__51514__35239__81435__23293__16592__88141__24236__09499__77845__77794__85972.1608721835.jpg?c=1?imbypass=on", category: "Bedding", description: "Drape your bed, your couch, or yourself in soft, fluffy art,100% polyester fleece", game: "Final Fantasy 15", price: "75.99", quantity: 10)
#Mug
finalfantasyfifteen3 = Item.create(name: "Prompto Mug", image: "https://i.etsystatic.com/22515413/r/il/e01d22/2520174286/il_794xN.2520174286_5tjr.jpg", category: "Mug" , description: "High quality white 11oz ceramic coffee mug. This is dishwasher and microwave safe." ,game: "Final Fantasy 15", price: "13.50", quantity: 20)
finalfantasyfifteen4 = Item.create(name: "Fierce Ignis Mug", image: "https://i.etsystatic.com/22515413/r/il/5f470a/3035889094/il_794xN.3035889094_50oe.jpg", category: "Mug" , description: "High quality white 11oz ceramic coffee mug. This is dishwasher and microwave safe." ,game: "Final Fantasy 15", price: "13.50", quantity: 20)
#Bag
finalfantasyfifteen8 = Item.create(name: "Pen Pencil Case Cosmetic Make Up Bag Storage Pouch ", image: "https://canary.contestimg.wish.com/api/webimage/59ce2391086da460a677080a-large.jpg?cache_buster=5c1942892defe356e9c3d23b367ea415" , category: "Bag" , description: "Spacious, sturdy, and sweet alternative to the traditional makeup bag" ,game: "Final Fantasy 15" , price: "14.00", quantity: 50)
finalfantasyfifteen9 = Item.create(name: "Ignis Tote Bag", image: "https://ih1.redbubble.net/image.294335271.3904/tb,840x840,medium-c,1,198,600,600-bg,f8f8f8.jpg" , category: "Bag" , description: "Totes deluxe. Sturdy and stylish with a vivid double-sided print" ,game: "Final Fantasy 15" , price: "23.06", quantity: 50)
finalfantasyfifteen10 = Item.create(name: "Ignis New Recipe Game PS Meme", image: "https://image.spreadshirtmedia.com/image-server/v1/mp/products/T636A2MPA1314PT26X36Y0D1027344290FS3627/views/2,width=550,height=550,appearanceId=2,backgroundColor=F2F2F2/ignis-new-recipe-game-ps-meme-ffxv-xbox-gift-duffle-bag.jpg" , category: "Bag" , description: "This large, square-shaped duffle bag is perfect for travel, a trip to the gym, or as a home for your sports equipment. Complete with shoulder strap and reinforced bottom, this bag is built to last." ,game: "Final Fantasy 15" , price: "31.99", quantity: 50)
finalfantasyfifteen11 = Item.create(name: "Cosplay Backpack cartoon Oxford Luminous School Bag Unisex", image: "https://res.cloudinary.com/webstore/image/fetch/w_500,c_limit,c_fit,f_auto,e_trim/https%3A%2F%2Fae01.alicdn.com%2Fkf%2FHTB143zORVXXXXb8XFXXq6xXFXXXY%2FGame-Final-Fantasy-15-Cosplay-Backpack-cartoon-Oxford-Luminous-School-Bag-Unisex.jpg" , category: "Bag" , description: "Spacious, sturdy, and sweet alternative to the traditional backpack" ,game: "Final Fantasy 15" , price: "50.99", quantity: 50)
#Keychain
finalfantasyfifteen15 = Item.create(name: "Prompto Revolver Keychain / Necklace Final Fantasy XV", image: "https://i.etsystatic.com/14466015/r/il/2b98c4/1793099327/il_794xN.1793099327_9fag.jpg", category: "KeyChain", description: "Handmade item,Necklace length: 24 Inches; Pendant height: 45 Millimeters; Pendant width: 20 Millimeters,Materials: Crystal Resin, Aluminum, Stainless Steel, Magic", game: "Final Fantasy 15" , price: "10.95" , quantity: 80 )
finalfantasyfifteen15 = Item.create(name: "Noctis fishing glitter epoxy double sided acrylic charm", image: "https://i.etsystatic.com/9912336/r/il/00e9e2/3593427691/il_794xN.3593427691_oysi.jpg", category: "KeyChain", description: "LET THE BOY FISH!!! an adorable charm of Noctis in his fishing gear and the whole kit and kaboodle! Chain to mimic the fishing line with a silver fish charm at the end! Charm comes with everything shown. 2.5 inches with glitter epoxy on one side!", game: "Final Fantasy 15" , price: "13.50" , quantity: 80 )
#Apparel
finalfantasyfifteen21 = Item.create(name: "Crest of Lucis T Shirt" , image: "https://i.etsystatic.com/26859792/c/1002/797/175/180/il/8c9903/2780355206/il_340x270.2780355206_6ds2.jpg", category: "Apparel", description: "Made from very soft cotton, this tee is really comfortable for an active lifestyle. With high quality print it allows one to express personality on the go.",game: "Final Fantasy 15", price:"18.96", quantity: 20 )
finalfantasyfifteen23 = Item.create(name: "Womens Slim Fit: Heir to the Throne / Final Fantasy XV / Noctis t-shirt" , image: "https://i.etsystatic.com/7282319/r/il/091132/1665017898/il_794xN.1665017898_qao6.jpg", category: "Apparel", description: "Fight in the name of the Crystal and show the world that you're the real King of Lucis!",game: "Final Fantasy 15", price:"27.00", quantity: 20 )
finalfantasyfifteen24 = Item.create(name: "Kingsglaive Cotton fitted face mask" , image: "https://i.etsystatic.com/24205951/r/il/d7962e/2462419193/il_794xN.2462419193_sk9n.jpg", category: "Apparel", description: "Every good glaive makes sure to protect the people of the city and their king by wearing a face mask. Just because we can’t go to cons doesn’t mean we can’t take some of our fav characters and bring them into everyday life with us! This is featuring one side of the face covering Nyx Ulric wears in the kingsglaive movie from ffxv.",game: "Final Fantasy 15", price:"10.00", quantity: 20 )
finalfantasyfifteen25 = Item.create(name: "Heroes T-Shirt" , image: "https://i.etsystatic.com/23584234/r/il/13a3d8/3527001711/il_794xN.3527001711_gd2u.jpg", category: "Apparel", description: "Constructed with 100% microfiber,knitted fabric that allows the skin to breathe and maintain a comfortable microclimate.Combed for softness and comfort.Vibrant print quality. Withstands an unlimited number of washes",game: "Final Fantasy 15", price:"24.43", quantity: 20 )
#Clock
finalfantasyfifteen15 = Item.create(name: "Clock - Noctis Caelum - Ignis Scientia - Gladioulus Amitica - Prompto Argentum", image: "https://i.etsystatic.com/9857393/r/il/69f865/1740261733/il_794xN.1740261733_5ugb.jpg", category: "Clock", description: "This Final Fantasy XV clock will come as a small wall clock, with a diameter of 8.75 inches, durable plastic frame, and a glass clock face. The artwork features the characters Noctis, Prompto, Gladio, and Ignis.", game: "Final Fantasy 15" , price: "29.99", quantity: 80 )
#Toy
finalfantasyfifteen39 = Item.create(name: "Gladiolus Amicitia Cosplay Necklace" , image: "https://i.etsystatic.com/15610404/r/il/586ade/1294990755/il_794xN.1294990755_9rj3.jpg", category: "Toy", description: "Cosplay Necklace for Gladio Amicitia.Necklace length: 21 Inches,Pendant height: 2.5 Inches,Materials: Glass, Gold, Rose gold.",game: "Final Fantasy 15", price:"", quantity: 20)
finalfantasyfifteen40 = Item.create(name: "Weapons Enamel Pins - Noctis Ignis Prompto Gladiolus Sword Daggers Gun" , image: "https://i.etsystatic.com/5784534/r/il/22616b/1509793230/il_794xN.1509793230_3uq7.jpg", category: "Toy", description: "Add some Final Fantasy XV arms flair to your collection! These are a great way to subtly express your fandom. Whether you wear just one, a pair, or the full set, you'll look fantastic!",game: "Final Fantasy 15", price:"12.00", quantity: 20)
finalfantasyfifteen41 = Item.create(name: "Best Print Store - Final Fantasy XV, Noctis and Luna Poster ,Wall Art ,Home Decor, No Frame" , image: "https://i.etsystatic.com/27150195/r/il/e88748/2983498164/il_794xN.2983498164_qnqc.jpg", category: "Toy", description: "We offer borderless, full color digital printing for posters. All posters are printed on premium 200 GSM gloss, suited for full-color digital art prints. Full colour poster printed on high quality. Rolled and sleeve in a plastic bag. Quality images for every living space!",game: "Final Fantasy 15", price:"9.89", quantity: 20)
finalfantasyfifteen45 = Item.create(name: "A New Recipe Ignis Apron" , image: "https://i.etsystatic.com/11644345/r/il/fb6d53/1993427766/il_794xN.1993427766_mmhz.jpg", category: "Toy", description: "The last layer of defense against spillage of all sorts, this adjustable A New Recipe Ignis Apron is a wonderful gift for yourself or a loved one. With plenty of coverage and pockets for utensils, forget cooking classes... this apron is all you need to become a gourmet chef! The last layer of defense against spillage of all sorts, this adjustable A New Recipe Ignis Apron is a wonderful gift for yourself or a loved one. With plenty of coverage and pockets for utensils, forget cooking classes...",game: "Final Fantasy 15", price:"26.00", quantity: 20)


#Final Fantasy 14  ---------------------
#Bedding
# finalfantasyfourteen1 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 14", price: "", quantity: 10)
# finalfantasyfourteen2 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 14", price: "", quantity: 10)
# finalfantasyfourteen3 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 14", price: "", quantity: 10)
# finalfantasyfourteen4 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 14", price: "", quantity: 10)
# #Mug
# finalfantasyfourteen3 = Item.create(name: "Dragoon Mug - I'm busy tanking...", image: "https://i.etsystatic.com/27190987/r/il/562fe1/3411698288/il_794xN.3411698288_3mp7.jpg", category: "Mug" , description: "Perfect for the Dragoon player who started a jump right when the aoe marker appeared under them." ,game: "Final Fantasy 14", price: "16.92", quantity: 20)
# finalfantasyfourteen4 = Item.create(name: "Warrior Of Light FFXIV Meteor Final Fantasy Gamer Gaming Coffee Tea Ceramic Mug 11oz", image: "https://i.etsystatic.com/26081505/r/il/98b3bf/3230848159/il_794xN.3230848159_k5zz.jpg", category: "Mug" , description: "Warm your soul with a nice cuppa out of this perfectly sized ceramic mug. It’s microwave safe and dishwasher safe and made of white, durable ceramic in an 11-ounce size. It's high-quality sublimation printing makes it the perfect gift for your true coffee, tea or hot chocolate lover." ,game: "Final Fantasy 14", price: "14.70", quantity: 20)
# #Bag
# finalfantasyfourteen8 = Item.create(name: "Soul Crystals Messenger Bag - all DoW/DoM including Reaper and Sage jobs, pick your favorite class MMORPG FF14 FFXIV", image: "https://i.etsystatic.com/12308374/c/729/580/112/221/il/fab1c6/3419885662/il_340x270.3419885662_aj31.jpg" , category: "Bag" , description: "Choose your soul before heading into battle! All of my original artwork of the soul crystals from FF14 are now available!" ,game: "Final Fantasy 14" , price: "39.50", quantity: 50)
# finalfantasyfourteen9 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 14" , price: "", quantity: 50)
# finalfantasyfourteen10 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 14" , price: "", quantity: 50)
# finalfantasyfourteen11 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 14" , price: "", quantity: 50)
# #Keychain
# finalfantasyfourteen15 = Item.create(name: "", image: "", category: "KeyChain", description: "", game: "Final Fantasy 14" , price: "" , quantity: 80 )
# finalfantasyfourteen15 = Item.create(name: "", image: "", category: "KeyChain", description: "", game: "Final Fantasy 14" , price: "" , quantity: 80 )
# #Apparel
# finalfantasyfourteen21 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 14", price:"", quantity: 20 )
# finalfantasyfourteen23 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 14", price:"", quantity: 20 )
# finalfantasyfourteen24 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 14", price:"", quantity: 20 )
# finalfantasyfourteen25 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 14", price:"", quantity: 20 )
# #Clock
# finalfantasyfourteen15 = Item.create(name: "", image: "", category: "Clock", description: "", game: "Final Fantasy 14" , price: "", quantity: 80 )
# #Toy
# finalfantasyfourteen39 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 14", price:"", quantity: 20)
# finalfantasyfourteen40 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 14", price:"", quantity: 20)
# finalfantasyfourteen41 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 14", price:"", quantity: 20)
# finalfantasyfourteen45 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 14", price:"", quantity: 20)


#---------------------------------------------------------------------------------

#CART
cart1 = Cart.create(user_id: User.first.id, purchase: false)
cart2 = Cart.create(user_id: User.second.id, purchase: false)

#CART_ITEM
cart_item1 = CartItem.create(cart_id: Cart.first.id, item_id: Item.first.id)
cart_item2 = CartItem.create(cart_id: Cart.second.id, item_id: Item.second.id)

puts "✅ Done seeding!"