# finalfantasyseven42 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 7", price: "", quantity: 10)
# finalfantasyseven12 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 7" , price: "", quantity: 50)
# finalfantasyseven27 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 7", price:"", quantity: 20 )
# finalfantasyten42 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10", price: "", quantity: 10)
# finalfantasyten12 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10" , price: "", quantity: 50)
# finalfantasyten27 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10", price:"", quantity: 20 )
#Final Fantasy 10.2 ----------
#Bedding
# finalfantasytentwo1 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo2 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo3 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo4 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo42 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo43 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo44 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo47 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
# finalfantasytentwo48 = Item.create(name: "", image: "", category: "Bedding", description: "", game: "Final Fantasy 10.2", price: "", quantity: 10)
#Mug
# finalfantasytentwo3 = Item.create(name: "", image: "", category: "Mug" , description: "" ,game: "Final Fantasy 10.2", price: "", quantity: 20)
# finalfantasytentwo4 = Item.create(name: "", image: "", category: "Mug" , description: "" ,game: "Final Fantasy 10.2", price: "", quantity: 20)
#Bag
# finalfantasytentwo8 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo9 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo10 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo11 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo12 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo13 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo14 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
# finalfantasytentwo26 = Item.create(name: "", image: "" , category: "Bag" , description: "" ,game: "Final Fantasy 10.2" , price: "", quantity: 50)
#Keychain
# finalfantasytentwo15 = Item.create(name: "", image: "", category: "KeyChain", description: "", game: "Final Fantasy 10.2" , price: "" , quantity: 80 )
# finalfantasytentwo15 = Item.create(name: "", image: "", category: "KeyChain", description: "", game: "Final Fantasy 10.2" , price: "" , quantity: 80 )
#Apparel
# finalfantasytentwo21 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo23 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo24 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo25 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo27 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo28 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo29 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo30 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo35 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo32 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo33 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo34 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
# finalfantasytentwo31 = Item.create(name: "" , image: "", category: "Apparel", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20 )
#Clock
# finalfantasytentwo15 = Item.create(name: "", image: "", category: "Clock", description: "", game: "Final Fantasy 10.2" , price: "", quantity: 80 )
# #Pens
# finalfantasytentwo32 = Item.create(name: "", image: "", category: "Pen", description: "", game: "Final Fantasy 10.2" , price: "", quantity: 80 )
# #Toy
# finalfantasytentwo39 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20)
# finalfantasytentwo40 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20)
# finalfantasytentwo41 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20)
# finalfantasytentwo45 = Item.create(name: "" , image: "", category: "Toy", description: "",game: "Final Fantasy 10.2", price:"", quantity: 20)
